config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :lists do
    resources :bookmarks
  end
  resources :bookmarks, only: :destroy

  root to: 'lists#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/bookmark.rb
class Bookmark < ApplicationRecord
  belongs_to :movie
  belongs_to :list

  validates :comment, length: { minimum: 6 }, presence: true
  validates_uniqueness_of :movie_id, scope: :list_id
end

app/models/list.rb
class List < ApplicationRecord
  has_many :bookmarks, dependent: :destroy
  has_many :movies, through: :bookmarks
  has_one_attached :photo
  validates :name, presence: true, uniqueness: true
end

app/models/movie.rb
class Movie < ApplicationRecord
  before_destroy :validate_bookmarks
  has_many :bookmarks

  validates :title, uniqueness: true, presence: true
  validates :overview, presence: true

  private

  def validate_bookmarks
    raise(ActiveRecord::InvalidForeignKey) unless bookmarks.empty?
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/bookmarks_controller.rb
class BookmarksController < ApplicationController
  def new
    @bookmark = Bookmark.new
  end

  def create
    @bookmark = Bookmark.new(bookmark_params)
    @list = List.find(params[:list_id])
    @bookmark.list = @list
    if @bookmark.save
      redirect_to list_path(@list)
    else
      render :new
    end
  end

  def destroy
    @bookmark = Bookmark.find(params[:id])
    @bookmark.destroy
    redirect_to list_path(@bookmark.list)
  end

  private

  def bookmark_params
    params.require(:bookmark).permit(:comment, :movie_id, :list_id)
  end
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
  def index
    @lists = List.all
  end

  def show
    @list = List.find(params[:id])
    @bookmark = Bookmark.new
  end

  def new
    @list = List.new
  end

  def create
    @list = List.new(list_params)
    if @list.save
      redirect_to list_path(@list)
    else
      render :new
    end
  end

  def destroy
    @list = List.find(params[:id])
    @list.destroy
    redirect_to list_path(@list)
  end

  private

  def list_params
    params.require(:list).permit(:name, :id, :photo)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookmarks_helper.rb
module BookmarksHelper
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsWatchList</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/lists/index.html.erb
<%= cl_image_tag("ydocv9aodzuv7sau2s4z",
      width: 400, height: 300, crop: :fill) %>

<div class="container">

<p><%= link_to 'Add list', new_list_path, class:'btn btn-primary'%></p>

  <h1>Your movie lists</h1>

  <% @lists.each do |list| %>
    <div class="list">
      <h3><%= link_to list.name, list_path(list) %></h3>
      <%= link_to image_tag(img, width: 500), list_path(list)%>
    </div>
  <% end  %>

</div>

app/views/lists/new.html.erb
<%= simple_form_for @list do |f| %>
  <%= f.input :name %>
  <%= f.input :photo, as: :file %>
  <br>
  <%= f.submit class: "btn btn-primary" %>
<% end %>
<br>
<%= link_to "Back to all lists", lists_path %>

app/views/lists/show.html.erb
<%= cl_image_tag @list.photo.key, height: 300, width: 400, crop: :fill %>

<h3><%= @list.name %></h3>
<br>
<p>Add a movie comment</p>
<%= simple_form_for [ @list, @bookmark ] do |f| %>
  <%= f.association :movie %>
  <%= f.input :comment %>
  <%= f.submit "add comment", class: "btn btn-primary" %>
<% end %>
<br>
<div class="card" style="width: 18rem;">
<% @list.bookmarks.each do |bookmark| %>
  <%= image_tag bookmark.movie.poster_url, alt: bookmark.movie.title %>
  <div class="card-body">
  <h4><%= bookmark.movie.title.upcase %></h4>
  <i class="far fa-star"></i> <small><%= bookmark.movie.rating %></small><br>
  <small class="card-text"><%= bookmark.movie.overview %></small>
  <br><br>
  <i class="fas fa-quote-left"></i> <i><%= bookmark.comment %></i>
  <br><br>
  <i class="far fa-trash-alt"></i>
  <small><%= link_to "Delete #{bookmark.movie.title}", bookmark_path(bookmark.id), method: :delete %></small>
<% end %>
  </div>
</div>
<br>
<%= link_to "Back to all lists", lists_path %>
<br>
<br>
<%= link_to "Delete #{@list.name}",
            list_path(@list),
            method: :delete,
            data: { confirm: "Are you sure?" } %>